### PR TITLE
Add Gitflow Action: build-statics.yaml

### PR DESCRIPTION
**Pull request by jonycfu**
** PR checklist **

- [X] Ensure you have added or ran the appropriate tests for your PR.
- [X] DCO signed

**What type of PR is this?**
A git workflow improvement (post-merge action)
**What this PR does / why we need it**:
Adds a trigger action for Frontend code changes -- building statics, move build to CLI, auto-commit build
**Which issue(s) this PR fixes**:
27084
**Special notes for your reviewer**:
I tested on separate branches. But a clean branch so that I don't include unwanted test commits.
See successful build ref: https://github.com/InfuseAI/piperider/runs/7176961260?check_suite_focus=true
**Does this PR introduce a user-facing change?**:
No

### CODE REVIEW

**Comment by jonycfu** [comment]
NOTE: Most of the code updated here is from `package-lock.json`, which we should commit.

**Comment by neighborhood999** [comment]
> NOTE: Most of the code updated here is from `package-lock.json`, which we should commit.

Got it. Are you considering using [yarn](https://yarnpkg.com/) or [pnpm](https://pnpm.io/) to generated lock files?
Using `package-loc.json` is fine, but I feel installation is too slow, haha.

**Review by neighborhood999 — COMMENTED** [review]
Looks great to me 💪.
I wonder should we need to remove static report files from our source control?

**Comment by jonycfu** [comment]
> Looks great to me 💪. I wonder should we need to remove static report files from our source control?

I think we should still keep them, as the CLI depends on those statics. I'm assuming you mean the result of `build:*` 

The one thing I want to remove from source control (but don't have a working solution yet) is `static_report/public/index.html`

**Review by neighborhood999 — APPROVED** [review]

**Review by popcornylu — APPROVED** [review]
LGTM. Smart method.

**Pull request merged**
