### PR TITLE
[Feature] - sc 30363 - UI layout v3 create run page oss

### PR DESCRIPTION
**Pull request by jonycfu**
**PR checklist**

- [ X] Ensure you have added or ran the appropriate tests for your PR.
- [ X] DCO signed

**What type of PR is this?**
feature
**What this PR does / why we need it**:
Update Core UI in OSS
**Which issue(s) this PR fixes**:
30363
**Special notes for your reviewer**:
https://www.loom.com/share/1d035b91d874466a89c8f086a88b433d

**Does this PR introduce a user-facing change?**: yes

* Updated the report html to have a flatter navigation structure, so there's no need to find information in separate pages

### CODE REVIEW

**Comment by popcornylu** [comment]
Can we expand/collapse only when clicking the triangle icon?  The problem I encounter is

1. I would like to see the table detail, but it toggle the expand/collapse
2. I click the eye icon, but it expand/collapse

**Comment by popcornylu** [comment]
Remove BUSINESS from the metric?
image

**Comment by popcornylu** [comment]
How about remove the "All"? e.g. All tables -> Tables
image

**Comment by popcornylu** [comment]
Do we remove the old index page?
image

And the current home redirect to first column of first table. Could we have at least a overall page?

**Comment by popcornylu** [comment]
Bug if there is no highlight in the sidebar, click one table item would collapse "All tables"
image

**Comment by popcornylu** [comment]
The default layout (with column valid% bar), the metric page layout would not show the two columns. It requires use to scroll the see the content in the two columns.
image

**Comment by popcornylu** [comment]
The column type filter is not useful. Can we remove it?
image

The column filter is not useful as well. Can we change to table filter or table+column filter?
image

**Comment by jonycfu** [comment]
> Do we remove the old index page? image
> 
> And the current home redirect to first column of first table. Could we have at least a overall page?

Hmm, I'm not sure what kind overall page is needed here that adds actual value for the user...as you can get the same information within the "master/detail" view. 

In other words, what's the value of the overall page? I just remember that we said this table-list page wasn't useful IIRC. 
Else, just adding a "empty index" page feels like an unnecessary +1 UX step

**Comment by jonycfu** [comment]
TODO: implement similar sidebar as documentation site

**Comment by popcornylu** [comment]
Some conclusions in the discussion
1. Put the original table list as the run home page.
2. Remove all toggles/function from `Tables`. (search, column filter, view details)
3. The sidebar collapse/expand behavior references our doc site.

**Comment by popcornylu** [comment]
Just to clarify. 

The current version would show the table list in an individual page. 
image



Could it put it in the `Tables` page?
image

**Comment by popcornylu** [comment]
@jonycfu 

There are two issues remaining
https://www.loom.com/share/036d508f494e4c5585908adb1ad455b4

The "top categories" layout mess up
1. Click Metrics
2. Select a text column
3. The top category layout mess up.

The tables menu expand when clicking metrics
1. Collapse the tables menu
2. Click metric
3. The tables menu item should not expand.

**Comment by jonycfu** [comment]
@popcornylu 

> The "top categories" layout mess up
> 
> Click Metrics
> Select a text column
> The top category layout mess up.
> The tables menu expand when clicking metrics
- Fixed. Now, tables will not be be auto-toggled upon navigating outside of tables (assertions, metrics)
- However, since there is no persisted storage to track navigation state over time. The default behavior of the accordion toggles are reset upon every new render of the page, which will cause the tables to fold when navigating away to assertions, metrics pages

> 
> Collapse the tables menu
> Click metric
> The tables menu item should not expand.
- Fixed: issue caused by legend plugin scoping on chartjs (BM charts)

**Review by popcornylu — APPROVED** [review]
LGTM

**Pull request merged**
