### PR TITLE
[Feature] Support running on dbt state with custom db/schema macros

### PR DESCRIPTION
**Pull request by david-k-johnson**
**PR checklist**

- [ X] Ensure you have added or ran the appropriate tests for your PR.
- [ X] DCO signed

**What type of PR is this?**
New Feature

**What this PR does / why we need it**:
Currently for running this project on a large dbt project that writes to multiple databases and schemas using custom dbt macros doe snot work at all.  This PR allows this to work and includes regex include(only)/exclude(filter) at command line to run on a substate of the entire large dbt project

**Which issue(s) this PR fixes**:
issue: 556

**Special notes for your reviewer**:
I am not sure if I followed all conventions correctly and if there are any gotchas that I am unaware of either in other databases types(tested throughly on snowflake) or conventions/patterns used for projects that are not dbt, but from reading the code this should work for everything.  I will say running this on a large DBT project that took over 12 hours to run, not having the ability to not fail everything on an error is very limiting/annoying.  I think catching errors and printing but continuing with everything else would be a nice addition, I just did not know how to represent that in the final html report.

**Does this PR introduce a user-facing change?**:
Yes, `piperider run` get the --only and --filter parameters to allow user to include tables using a regex and filter to exclude tables using a regex

### CODE REVIEW

**Comment by popcornylu** [comment]
Thanks for your PR. 

Regarding to only/filter, one trick you can use is to use [dbt node selection](https://docs.getdbt.com/reference/node-selection/syntax) as filter. Here is the example

```
# run my_model and all children
dbt run -s my_model+
# piperider would run the affected models, based on the run_result.json
piperider run --dbt-state target/
```

The limitation is you have to run dbt before run piperider whenever you want to change another filter. In the future, we would allow some command like 

```
dbt list -s my_model+ | piperider run --dbt-id-file -
```
That is, you don't need to run/build dbt before running piperider.

**Comment by david-k-johnson** [comment]
> Thanks for your PR.
> 
> Regarding to only/filter, one trick you can use is to use [dbt node selection](https://docs.getdbt.com/reference/node-selection/syntax) as filter. Here is the example
> 
> ```
> # run my_model and all children
> dbt run -s my_model+
> # piperider would run the affected models, based on the run_result.json
> piperider run --dbt-state target/
> ```
> 
> The limitation is you have to run dbt before run piperider whenever you want to change another filter. In the future, we would allow some command like
> 
> ```
> dbt list -s my_model+ | piperider run --dbt-id-file -
> ```
> 
> That is, you don't need to run/build dbt before running piperider.

Thanks both those commands seem useful but I think solve different problems.  only/filter allows a few things that the above examples do not

1.  only/filter work for all types of piperider configs not just dbt related ones
2. only/filter works with a regex and is super handy for the edit/debug cycle
3. only/filter are better if I want to maybe skip all intermediate models or run all the models in one directory, etc. 
4. include/exclude would be more useful if they accepted regexes as well
 
Hope that helps explain why I fond it useful.

BTW what are your thoughts on the rest of the PR?

**Comment by david-k-johnson** [comment]
I will look into these error in the next day or two and get them all to pass, I have some suspensions but it might require more changes.

**Comment by david-k-johnson** [comment]
So I got most things working now, how do I see the cypress pictures/videos to see what the actual problem is?

**Comment by david-k-johnson** [comment]
I see the major issue, will work on this in next few days, need to refactor code to get this to work for dbt and non-dbt instances

**Comment by david-k-johnson** [comment]
Finally got all tests to pass, but I think many unit tests should of failed before getting to e2e but that is another story:). Please let me know of concerns/questions as soon as you can.

**Comment by kentwelcome** [comment]
For wording suggestions. Currently, we use `--only/--filter` as the command line option. Is it able to use more specific wording? Such like `--include-tables/--exclude-tables`

**Comment by david-k-johnson** [comment]
> For wording suggestions. Currently, we use `--only/--filter` as the command line option. Is it able to use more specific wording? Such like `--include-tables/--exclude-tables`

It could but I did not want to conflate it with the already existing include/exclude tables feature. but it is up to you on what you would like to name it.

**Comment by kentwelcome** [comment]
> > For wording suggestions. Currently, we use `--only/--filter` as the command line option. Is it able to use more specific wording? Such like `--include-tables/--exclude-tables`
> 
> It could but I did not want to conflate it with the already existing include/exclude tables feature. but it is up to you on what you would like to name it.

Got it! I will prefer to keep your current naming.

**Comment by david-k-johnson** [comment]
Is this PR being considered, have not seen any comments on this?

**Review by popcornylu — CHANGES_REQUESTED** [review]
**In terms of custom databases**
We have tried and it works! Currently, it loops for each (db, schema) combination, we will think if we can implement by non-loop solution in the future. Not necessary to be changed in this PR

**In terms of only/filter**
It does not work for no `--dbt-state` case. It will show
```
Error: 'NoneType' object is not iterable
```
The reason is that the tables to profile is reflected by metadata in db. There are two options for this PR
1. Make it work in no `--dbt-state` case
2. Work without error and indicate that the option only works with `--dbt-state` option.

Thanks for your contribution again :)

**Comment by david-k-johnson** [comment]
> **In terms of custom databases** We have tried and it works! Currently, it loops for each (db, schema) combination, we will think if we can implement by non-loop solution in the future. Not necessary to be changed in this PR
> 
> **In terms of only/filter** It does not work for no `--dbt-state` case. It will show
> 
> ```
> Error: 'NoneType' object is not iterable
> ```
> 
> The reason is that the tables to profile is reflected by metadata in db. There are two options for this PR
> 
> 1. Make it work in no `--dbt-state` case
> 2. Work without error and indicate that the option only works with `--dbt-state` option.
> 
> Thanks for your contribution again :)

How are the tests passing?  Did you test the latest version because I thought it was working when not using dbt state?

**Comment by popcornylu** [comment]
In a project with dbt data source

It works if
```
$ piperider run --only 'my_pattern' --dbt-state target/
```

It will raise error
```
$ piperider run --only 'my_pattern'
Error: 'NoneType' object is not iterable
```


The debug message by `--debug`
image

**Comment by popcornylu** [comment]
Close this PR because #572 implemented the multiple (custom) databases and schemas

**Pull request closed without merging**
